name: Python package

on:
  push:
    branches:
      - dev2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Vérifie le code dans le dépôt

      - name: Set up Python
        uses: actions/setup-python@v4  # Configure Python dans l'environnement
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install pylint
        run: pip install pylint  # Cette étape installe pylint

      - name: Test main.py with pylint
        run: |
          pylint main.py --fail-under=8  # Vérifie la qualité du code avec pylint

      - name: Run main.py and capture output
        id: run-main
        run: |
          python main.py > output.txt  # Exécute le script et capture la sortie dans un fichier

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"  # Affiche la version de Python

      - name: Check for confusion matrix in output
        run: |
          if grep -q "matrice de confusion" output.txt; then
            echo "matrice de confusion found in output."
          else
            echo "matrice de confusion not found in output." && exit 1

          fi
      - name: Model accuracy
        run: | 
          if python tests/score.py | grep -q "le modèle semble  pas si mal"; then
            echo "accuracy >0.8 plus de 80% bonnes réponses sur les données de test pour validation"
          else 
            echo "accuracy <=0.8 moins de 80% bonnes réponses sur les données de test pour validation" && exit 1
          fi
